name: simple-todo
version: 1.0.0
title: Simple Todo List
description: A clean and minimal todo list app for managing your daily tasks. Add, complete, and delete todos with an intuitive interface.

sharing:
  mode: secret_link
  expires_after_days: 30

capabilities:
  storage:
    enabled: true

build:
  entry: src/App.tsx
  output: dist/
